## name:     Koda Dark
## author:   oskarnurm (ported from koda.nvim)
## upstream: https://github.com/oskarnurm/koda.nvim


font_family     JetBrains Mono
font_size       10.0

# Set inner padding (space inside the window)
window_padding_width 10
#
# # Set padding for the window border (outside the terminal)
window_padding_height 10
#

# The basic colors
foreground              #b0b0b0
background              #181818

selection_foreground    #181818

selection_background    #b0b0b0

# Cursor colors
cursor                  #ffffff
cursor_text_color       #181818


# URL underline color when hovering with mouse
url_color               #777777

# Kitty window border colors
active_border_color     #ffffff
inactive_border_color   #272727
bell_border_color       #b0b0b0

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #181818

active_tab_background   #b0b0b0
inactive_tab_foreground #50585d
inactive_tab_background #161616
tab_bar_background      #181818


# Colors for marks (marked text in the terminal)
mark1_foreground #181818

mark1_background #ffffff
mark2_foreground #181818

mark2_background #b0b0b0
mark3_foreground #181818

mark3_background #777777

# The 16 terminal colors

# black
color0  #272727
color8  #50585d

# red
color1  #c07070
color9  #c07070

# green
color2  #7a9f7a
color10 #7a9f7a

# yellow
color3  #a89060
color11 #a89060

# blue
color4  #6080a0
color12 #6080a0

# magenta
color5  #906090
color13 #906090

# cyan
color6  #507878
color14 #507878

# white
color7  #b0b0b0
color15 #ffffff
